### ISSUE TITLE
Change Start Date to Stardate

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-ordered-mission-posts#1]
Update Start Date to say Stardate.

Labels: Mission Start Date to Stardate

SQL Column from nova_ext_ordered_post_start_date to nova_ext_ordered_post_stardate

**Comment by pawanmall157** [comment]
Fixed

**Comment by reecesavage** [comment]
This is still showing as Startdate and Start Date. It should be Stardate

![image](https://user-images.githubusercontent.com/15860882/106503028-c519d100-648a-11eb-883c-5c4754920bde.png)

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
Checked is fixed
